---
title: "Predictive Accuracy of ACS Risk Calculator in determining intra- and postoperative complications in Pakistani population"
author: Naveed Aman Pasha
date: February 15, 2019 
output:
        word_document:
                toc: true
                toc_depth: 2
                number_sections: true
                theme: darkly
                highlights: pygments
                fig_width: 7
                fig_height: 6
                fig_caption: true
                df_print: kable
                code_folding: hide
---

# Abstract

Clear understanding of the risks and benefits of any surgical procedure is
crucial for both surgeon and patient when committing to any surgical treatment.
Surgeons are interested in the ability of the patient to survive the procedure
without harm. Patients are interested primarily in the gravity of the surgery
and secondarily in the expected length of hospital stay in order to manage their
lives according to what best suits patient care. Unfortunately there exists no
validated surgical risk calculator for the Pakistani population. The objective
of this study is to ascertain the accuracy of the American College of Surgeons
National Survey on Quality Improvement Project risk calculator in predicting
intra- and postoperative adverse outcomes as well as postoperative length of
stay.

# Introduction

Undertaking surgical procedures involves a decision making process shared
between the surgeon and the patient. Clear understanding of the procedure, its
risks and benefits is essential for patients to make an informed decision.
Therefore, patients need to know not only what complications can take place but
also the probability of those complications in order to weigh them against the
benefits. Knowing the probability of complications becomes especially vital in
emergency setting when patients are confronted with a sudden decision where both
affirmation and negation have drastic consequences. Unfortunately, there exists
no calculator for post-operative morbidity and mortality in the emergency
setting for the entire South-East Asia Region. 

-- need to fill --

# Rationale

-- need to fill --

# Objective

The primary objective of this study is assess the accuracy of the ACS NSQIP risk
calculator in estimating the probability of post-operative mortality and
morbidity in patients of the Pakistani population undergoing elective and
emergent surgeries.

# Operational Definitions

These operational definitions have been adapted from the [ACS risk calculator
website](https://riskcalculator.facs.org/RiskCalculator/PatientInfo.jsp)

1. Functional Status

- Independent: the patient does not require assistance from another person for
  any activities of daily living. This includes a person who is able to function
  independently with prosthetics, equipment or devices
- Partially dependent: the patient requires some assistance from another person
  for activities of daily
- Totally dependent: the patient requires total assistance for all activities of
  daily living

2. ASA classification

- ASA 1: Normal healthy patient
- ASA 2: Patient with mild systemic disease
- ASA 3: Patient with severe systemic disease
- ASA 4: Patient with severe systemic disease that is a constant threat to life
- ASA 5: Moribund patient who is no expected to survive without operation

3. Steroid Use

This includes any administration of steroids greater a single pulse dose or a
short taper course less than 10 days.

4. Ascites

The presence of fluid accumulation in peritoneal cavity noted on physical
examination, abdominal ultrasound or abdominal CT/MRI.

5. Systemic Sepsis

Any patient displaying signs and symptoms of:

- Systemic inflammatory response syndrome
- Sepsis
- Septic shock

6. Ventilator Requirement

This does not include patients requiring CPAP for sleep apnoea.

7. Disseminated Cancer

The patient has a primary cancer that has metastasized to a major organ AND
meets at least one of the following:

- active treatment for the cancer within one year of the surgery date. If the surgical procedure is the treatment for the
metastatic cancer, answer "Yes"
- the patient has elected not to receive treatment for the metastatic disease
- the patient's metastatic cancer has been deemed untreatable

Does not include patients with

- Chronic lymphocytic leukemia,
- Chronic myelogenous leukemia,
- Lymphomas of stages I through III or multiple myeloma

8. Presence of Diabetes

This will not include patients whose diabetes is controlled by diet alone.

9. Congestive Heart Failure

- Newly diagnosed CHF within previous 30 days
- Diagnosis of chronic CHF with signs or symptoms of CHF in the 30 days prior to
  proposed surgery

10. Current Smoker

A current smoker will not include patients who consumed cigars, pipes or chewing
tobacco. 

11. Severe COPD

Severe COPD will be defined as:

- Functional disability from COPD
- Hospitalisation in the past fro treatment of COPD
- Chronic bronchodilator therapy with oral or inhaled agents
- FEV<sub>1</sub> of < 75% of predicted
- Does not include patients whose only pulmonary disease is asthma
- Does not include patients with diffuse interstitial fibrosis or sarcoidosis

12. Requirement for Dialysis

- Acute or chronic renal failure requiring peritoneal dialysis, hemodialysis,
  hemofiltration or ultrafiltration within 2 weeks of proposed surgery
- If a patient refuses dialysis but requires it, the answer will be "yes"

13. Acute Renal Failure

A clinical condition associated with rapid decline of the kidney function. The
patient meets one of the following:

- Increased BUN on two measurements AND two creatinine results > 3mg/dL
- Surgeon or physician has documented Acute Renal Failure AND one of the
  following
  - Increased BUN on two measurements
  - Two Cr results > 3 mg/dL

14. Pneumonia

- Infection of the lungs, diagnosed using both radiologic (i.e., infiltrate, consolidation or opacity, cavitation) and clinical (e.g., fever, leukopenia/leukocytosis, culture results, patient symptoms) criteria..

15. Cardiac complication

- Cardiac arrest: The absence of cardiac rhythm or presence of a chaotic cardiac rhythm requiring the initiation of CPR, which includes chest compressions.
- Myocardial infarction: ECG changes, new elevation in troponin, or physician diagnosis.

16. Surgical site infection (SSI)

-  Superficial Incisional SSI: infection that involves only skin or subcutaneous tissue of the incision. It also includes either: purulent drainage, positive culture, signs/symptoms of infection and the incision is deliberately opened by the surgeon or diagnosis by the attending physician.
-  Deep Incisional SSI: infection that appears to be related to the operation and involves deep soft tissues (for example, fascial and muscle layers) of the incision. It also includes either: purulent drainage, spontaneous dehiscence, deliberate opening by the surgeon, abscess involving the deep incision, or diagnosis by the attending physician.
-  Organ Space SSI: infection that involves any part of the anatomy (for example, organs or spaces), other than the incision, which was opened or manipulated during an operation. It also includes either: purulent drainage, positive culture, abscess, or diagnosis by the attending physician.

17. Urinary tract infection

- Bladder infection, diagnosed using a combination of clinical symptoms and laboratory confirmation (e.g., urine culture, pyuria, positive dipstick) or initiation of appropriate antimicrobial therapy.

18. Venous thromboembolism / blood clot

- The identification of a new thrombus within the venous system, described in studies as present in the superficial or deep venous systems but requires therapy. This diagnosis is confirmed by a duplex, venogram, CT scan or other imaging modality, AND the patient requires treatment with anticoagulation therapy and/or placement of a vena cava filter or clipping of the vena cava.

19. Renal failure

-  Progressive renal insufficiency: a rise in creatinine of >2 mg/dl from preoperative value, but with no requirement for dialysis.
-  Acute renal failure requiring dialysis: A patient who did not require dialysis preoperatively, worsening of renal dysfunction postoperatively requiring hemodialysis, peritoneal dialysis, hemofiltration, hemodiafiltration, or ultrafiltration.

20. Ileus

- Prolonged Postoperative NPO or NGT Use: Prolonged NPO status or NGT use for
  suctioning or decompression, more than 3 days postoperatively (postoperative day 4 or later) OR
  reinsertion of NGT or reinstating NPO status any time postoperative day 4 or later within 30 days.

21. Anastomotic Leak

- There was a leak of endoluminal contents through an anastomosis. This could
  include air, fluid, GI contents, or contrast material. The presence of an
  infection/abscess thought to be related to an anastomosis, even if the leak
  cannot be definitively identified as visualized during an operation, or by
  contrast extravasation, would still be considered an anastomotic leak if this
  is indicated by the surgeon including
  - Without a documented treatment intervention
  - Treated with NPO, Antibiotics, TPN or other non-interventional, non-operative means
  - Treated with percutaneous/radiological/endoscopic interventional means- i.e.,- percutaneous drainage with or without indwelling drain. endoscopic stent, etc.
  - Treated with re-operation

22. Return to Operating Room

- Return to the operating room for additional surgery that was not planned at the time of the initial surgery. 

# Methods

Approval for the study will be taken from the Ethical Review Committee of the
Aga Khan University Hospital.

## Study Design

This will be a single centre descriptive longitudinal study. 

## Study Setting

The study conducted at the Aga Khan University Hospital in the Departments of
Surgery and Emergency Medicine. Surgeries will be performed in the operating
rooms. Patients will be observed postoperatively in the General Ward, High
Dependency Units or outpatient clinics (based on patient condition).

## Inclusion criteria

The study population will comprise of adult patients undergoing any of the
following surgical procedures:

- Thyroidectomy (total or partial)
- Parathyroidectomy
- Diversion or resective colonic surgery
  - Right hemicolectomy
  - Left hemicolectomy
  - Total colectomy
  - Lower Anterior Resection
  - Abdomino-perineal resection
- Pancreatic Procedures
  - Whipple procedure
  - Distal Pancreatectomy

## Data Collection and Management

Pertinent patient variables that will be collected are:

- Age
- Gender
- BMI
- Functional Status
- Whether surgery is emergent
- ASA Class
- Steroid use for chronic condition
- Ascites within last 30 days prior to presentation
- Systematic sepsis within previous 48 hours
- Presence of congestive heart failure on presentation
- Presence of acute renal failure on presentation
- Presence of disseminated cancer
- Presence of diabetes (none, on oral hypoglycemics, on insulin)
- Presence of hypertension requiring medication
- Current Smoker for last one year
- Presence of severe COPD
- Dialysis Dependent
- Ventilator requirement 48 hours prior to planned surgery

These variables will be collected on a preformed performa. The
data gathered by the performa will be entered into the [ACS risk
calculator](https://riskcalculator.facs.org). The risk of each of the following
outcomes will be noted:

- Pneumonia
- Cardiac Complication
- Surgical Site Infection
- Urinary Tract Infection
- Renal Failure
- Ileus
- Anastomotic Leak
- Return to Operating Room

The patients will be followed for 90 days postoperatively and outcomes of
interest will also be noted at 30 and 90 days postoperatively. These data will be stored online in the form of
spreadsheet under password protection. Once data collection is complete, hard
copies of the performas will be destroyed. Data will be anonymised in order to
protect patient privacy.

## Duration of Study

One to two years after the approval of synopsis.

## Sample Size

-- to be calculated --

## Duration of Study

Non-probability consecutive sampling.

## Data Analysis

The statistical analysis will be performed using the R statistical programming
language and environment. Distributions of the predicted probabilities of mortality
as well as each morbidity will be plotted. Receiver operating curves will be
plotted for these distributions by comparing the estimated probabilities of each
outcome with the actual observed outcomes and the area under the curve will be
calculated. Data will be gathered prospectively.

# Expected Outcomes of the Study

Provision of surgical risk calculator in the emergency setting will be
a tremendous asset to patients. The risk calculator will assist in weighing the
risks and benefits of the emergency surgery by providing the probability of
adverse outcomes. It will aid patients in justifying the cost of the surgical
procedure. It will aid surgeons in tailoring selection of candidates for surgery
in cases where benefits of surgery are equivocal.

# Dissemination of Results

Results are intended to be submitted for publication as
free access so that the risk calculator may be freely available to surgeons
across for application. Study results will be reported in accordance with the
STROBE guidelines.
